name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Compile
        run: php src/main.php

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Clone the gh-pages branch
          git clone --branch=gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cd gh-pages

          # Copy contents of dist to the gh-pages branch
          cp -r ../dist/* .

          # Add all files to git
          git add .

          # Commit and push changes
          git commit -m 'Deploy to GitHub Pages' || echo "No changes to commit"
          git push
